export const PAINTER_THEMES = [
  {
    id: 'vangogh_starry',
    name_en: 'Van Gogh · Starry Night',
    name_zh: '梵谷·星夜',
    primary: '#1B3B6F',
    secondary: '#F4D03F',
    accent: '#F39C12',
    bg: '#0B1020',
  },
  {
    id: 'monet_waterlilies',
    name_en: 'Monet · Water Lilies',
    name_zh: '莫內·睡蓮',
    primary: '#5DADE2',
    secondary: '#ABEBC6',
    accent: '#F9E79F',
    bg: '#F4F9FB',
  },
  {
    id: 'klimt_gold',
    name_en: 'Klimt · Golden Leaf',
    name_zh: '克林姆·金色',
    primary: '#D4AC0D',
    secondary: '#FAD7A0',
    accent: '#CD6155',
    bg: '#FEF9E7',
  },
  {
    id: 'picasso_blue',
    name_en: 'Picasso · Blue Period',
    name_zh: '畢卡索·藍色時期',
    primary: '#154360',
    secondary: '#5DADE2',
    accent: '#A569BD',
    bg: '#EBF5FB',
  },
  {
    id: 'hokusai_wave',
    name_en: 'Hokusai · Great Wave',
    name_zh: '北齋·神奈川沖浪裏',
    primary: '#154360',
    secondary: '#1ABC9C',
    accent: '#E67E22',
    bg: '#ECF0F1',
  },
  {
    id: 'matisse_cutouts',
    name_en: 'Matisse · Cut-Outs',
    name_zh: '馬諦斯·剪紙',
    primary: '#E74C3C',
    secondary: '#3498DB',
    accent: '#F1C40F',
    bg: '#FDFEFE',
  },
  {
    id: 'rothko_sunset',
    name_en: 'Rothko · Sunset Fields',
    name_zh: '羅斯科·暮色',
    primary: '#922B21',
    secondary: '#E59866',
    accent: '#AF601A',
    bg: '#FDF2E9',
  },
  {
    id: 'dali_surreal',
    name_en: 'Dali · Surreal Sands',
    name_zh: '達利·超現實',
    primary: '#7D6608',
    secondary: '#F8C471',
    accent: '#1F618D',
    bg: '#FEF5E7',
  },
  {
    id: 'turner_mist',
    name_en: 'Turner · Misty Harbor',
    name_zh: '透納·迷霧港灣',
    primary: '#566573',
    secondary: '#AEB6BF',
    accent: '#F7DC6F',
    bg: '#F8F9F9',
  },
  {
    id: 'pollock_drip',
    name_en: 'Pollock · Drip Energy',
    name_zh: '波洛克·飛濺',
    primary: '#2E86C1',
    secondary: '#F4D03F',
    accent: '#C0392B',
    bg: '#FBFCFC',
  },
  {
    id: 'seurat_pointillism',
    name_en: 'Seurat · Pointillism',
    name_zh: '修拉·點彩',
    primary: '#1F618D',
    secondary: '#F7DC6F',
    accent: '#52BE80',
    bg: '#FDFEFE',
  },
  {
    id: 'frida_viva',
    name_en: 'Frida · Viva Color',
    name_zh: '芙烈達·生命色塊',
    primary: '#196F3D',
    secondary: '#EC7063',
    accent: '#F4D03F',
    bg: '#FEF9E7',
  },
  {
    id: 'cezanne_mountains',
    name_en: 'Cézanne · Mountains',
    name_zh: '塞尚·群山',
    primary: '#2E86C1',
    secondary: '#A9CCE3',
    accent: '#58D68D',
    bg: '#EBF5FB',
  },
  {
    id: 'bosch_fantasy',
    name_en: 'Bosch · Dreamscape',
    name_zh: '波希·夢境',
    primary: '#512E5F',
    secondary: '#A569BD',
    accent: '#F5B041',
    bg: '#FDF2E9',
  },
  {
    id: 'rembrandt_chiaroscuro',
    name_en: 'Rembrandt · Chiaroscuro',
    name_zh: '林布蘭·明暗',
    primary: '#6E2C00',
    secondary: '#CA6F1E',
    accent: '#F7DC6F',
    bg: '#FBEEE6',
  },
  {
    id: 'vermeer_light',
    name_en: 'Vermeer · Soft Light',
    name_zh: '維梅爾·靜光',
    primary: '#1F618D',
    secondary: '#F7DC6F',
    accent: '#A2D9CE',
    bg: '#FEF9E7',
  },
  {
    id: 'kandinsky_abstract',
    name_en: 'Kandinsky · Abstract Rhythm',
    name_zh: '康丁斯基·抽象律動',
    primary: '#2E86C1',
    secondary: '#F4D03F',
    accent: '#E74C3C',
    bg: '#FBFCFC',
  },
  {
    id: 'chagall_dream',
    name_en: 'Chagall · Midnight Dream',
    name_zh: '夏卡爾·午夜夢',
    primary: '#1A237E',
    secondary: '#5C6BC0',
    accent: '#FFCA28',
    bg: '#E8EAF6',
  },
  {
    id: 'yayoi_polka',
    name_en: 'Yayoi Kusama · Polka Infinity',
    name_zh: '草間彌生·圓點無限',
    primary: '#C0392B',
    secondary: '#F7DC6F',
    accent: '#27AE60',
    bg: '#FDEDEC',
  },
  {
    id: 'haring_pop',
    name_en: 'Keith Haring · Pop Lines',
    name_zh: '哈林·塗鴉線條',
    primary: '#212F3C',
    secondary: '#E74C3C',
    accent: '#F1C40F',
    bg: '#FDFEFE',
  },
];

export const CORAL_COLOR = '#FF7F50';

export const AI_MODELS = {
  gemini: [
    'gemini-2.5-flash',
    'gemini-3-flash-preview',
    'gemini-2.5-flash-lite',
    'gemini-3-pro-preview',
  ],
  openai: ['gpt-4o-mini', 'gpt-4.1-mini'],
  anthropic: ['claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022'],
  xai: ['grok-4-fast-reasoning', 'grok-4-1-fast-non-reasoning'],
};
